language: android
dist: trusty
android:
  components:
    - build-tools-26.1.1
    - android-29
    - extra
   licenses:
    - 'android-sdk-preview-license-24333f8a63b6825ea9c5514f83c2829b004d1fee'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
env:
 global:
  - Android_API=29
  - ANDROID_BUILD_TOOLS=26.1.1

before_install:
 - chmod +x gradlew
script: 
 - ./gradlew build --info
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

